version: '3.8'
services:
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:443"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_ENABLE_TLS: true
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data: